emit:
  - '@azure-tools/typespec-autorest'
  - '@azure-tools/typespec-providerhub-controller'
options:
  '@azure-tools/typespec-autorest':
    emitter-output-dir: '{output-dir}'
    arm-types-dir: ../../../../../common-types/resource-management # Default: {project-root}/../../common-types/resource-management
    azure-resource-provider-folder: ./swagger/SecretManagementSampleProvider/resource-manager
    output-file: '{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/secretmanagementsample.json'
    examples-directory: ./examples
  '@azure-tools/typespec-providerhub-controller':
    emitter-output-dir: '{output-dir}/generated'
    code-kind: model
