./generateExamples.sh smfDeployment smfDeployment1 smfdeploymentget.txt smfdeploymentput.txt SmfDeployment
./generateExamples.sh nrfDeployment nrfDeployment1 nrfdeploymentget.txt nrfdeploymentput.txt NrfDeployment
./generateExamples.sh amfDeployment amfDeployment1 amfdeploymentget.txt amfdeploymentput.txt AmfDeployment
./generateExamples.sh upfDeployment upfDeployment1 upfdeploymentget.txt upfdeploymentput.txt UpfDeployment
./generateExamples.sh nssfDeployment nssfDeployment1 nssfdeploymentget.txt nssfdeploymentput.txt NssfDeployment
./generateExamples.sh mmeDeployment mmeDeployment1 mmedeploymentget.txt mmedeploymentput.txt MmeDeployment
./generateExamples.sh emsDeployment emsDeployment1 emsdeploymentget.txt emsdeploymentput.txt EmsDeployment
./generateExamples.sh paasDeployment paasDeployment1 paasdeploymentget.txt paasdeploymentput.txt PaasDeployment
./generateExamples.sh cluster cluster1 clusterdeploymentget.txt clusterdeploymentput.txt Cluster
