mv smfdeploymentget.json smfdeploymentget.txt
mv smfdeploymentput.json smfdeploymentput.txt
mv nrfdeploymentget.json nrfdeploymentget.txt
mv nrfdeploymentput.json nrfdeploymentput.txt
mv amfdeploymentget.json amfdeploymentget.txt
mv amfdeploymentput.json amfdeploymentput.txt
mv upfdeploymentget.json upfdeploymentget.txt
mv upfdeploymentput.json upfdeploymentput.txt
mv nssfdeploymentget.json nssfdeploymentget.txt
mv nssfdeploymentput.json nssfdeploymentput.txt
mv mmedeploymentget.json mmedeploymentget.txt
mv mmedeploymentput.json mmedeploymentput.txt
mv emsdeploymentget.json emsdeploymentget.txt
mv emsdeploymentput.json emsdeploymentput.txt
mv paasdeploymentget.json paasdeploymentget.txt
mv paasdeploymentput.json paasdeploymentput.txt
mv clusterdeploymentget.json clusterdeploymentget.txt
mv clusterdeploymentput.json clusterdeploymentput.txt
mv CreateOrUpdate.json CreateOrUpdate.txt
mv Delete.json Delete.txt
mv Get.json Get.txt
mv ListByResourceGroup.json ListByResourceGroup.txt
mv ListBySubscription.json ListBySubscription.txt
mv UpdateTags.json UpdateTags.txt
