emit:
  - '@azure-tools/typespec-autorest'
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: ../../../../../carbon/Carbon.Management
    examples-directory: ./examples
    output-file: main.json