emit:
  - '@azure-tools/typespec-autorest'
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
options:
  '@azure-tools/typespec-autorest':
    arm-types-dir: "{project-root}/../../../common-types/resource-management"
    azure-resource-provider-folder: "resource-manager"
    emitter-output-dir: "{project-root}/../.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/aadApplication.json"