output-dir: "{project-root}"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{output-dir}"
    azure-resource-provider-folder: ./swagger/Standards/resource-manager
    examples-directory: ./examples
    new-line: lf
  "@azure-tools/typespec-providerhub-controller":
    emitter-output-dir: "{output-dir}/generated"
    registration-output-path: "{output-dir}/manifest"
