import "@typespec/rest";
import "@typespec/versioning";
import "@azure-tools/typespec-autorest";
import "@azure-tools/typespec-azure-core";
import "@azure-tools/typespec-azure-resource-manager";

using TypeSpec.Http;
using TypeSpec.Rest;
using TypeSpec.Versioning;
using Azure.ResourceManager;
using Autorest;

#suppress "@azure-tools/typespec-azure-core/casing-style" "The names of Namespace types must use PascalCaseTypeSpec"
@armProviderNamespace
@service({
  title: "Foundational ARM Client",
  version: "2023-08-22-preview",
})
@doc("AddressRecord Provider")
@useDependency(Azure.ResourceManager.Versions.v1_0_Preview_1)
namespace Microsoft.AzureCIS;

@doc("AddressRecord properties")
model AddressRecordResourceProperties {
  @doc("Gets or sets the IP Address in String format")
  valueString: string;

  @doc("Provisioning state")
  @visibility("read")
  provisioningState?: AddressRecordProvisioningState;
}

@doc("AddressRecord Resource")
model AddressRecordResource is ProxyResource<AddressRecordResourceProperties> {
  @doc("The name of resource.")
  @pattern("^[a-zA-Z0-9-]{3,24}$")
  @key("resourceName")
  @segment("addressRecord") // start with lower case
  @visibility("read")
  @path
  name: string;
}

@doc("Provisioning status of the resource.")
enum AddressRecordProvisioningState {
  ...ResourceProvisioningState,

  @doc("Accepted State")
  Accepted,
}

#suppress "@azure-tools/typespec-azure-resource-manager/no-resource-delete-operation" "The resource must have a delete operation.TypeSpec"
@armResourceOperations
interface AddressRecords {
  createOrUpdate is ArmResourceCreateOrUpdateAsync<AddressRecordResource>;
  listBySubscription is ArmListBySubscription<AddressRecordResource>;
  listByResourceGroup is ArmResourceListByParent<AddressRecordResource>;
  get is ArmResourceRead<AddressRecordResource>;
}
