import "@typespec/rest";
import "@typespec/versioning";
import "@azure-tools/typespec-autorest";
import "@azure-tools/typespec-azure-core";
import "@azure-tools/typespec-azure-resource-manager";

using TypeSpec.Http;
using TypeSpec.Rest;
using TypeSpec.Versioning;
using Azure.ResourceManager;
using Autorest;

#suppress "@azure-tools/typespec-azure-core/casing-style" "The names of Namespace types must use PascalCaseTypeSpec"
@armProviderNamespace
@service({
  title: "Foundational ARM Client",
  version: "2023-08-22-preview",
})
@doc("CanonicalNameRecord Provider")
@useDependency(Azure.ResourceManager.Versions.v1_0_Preview_1)
namespace Microsoft.AzureCIS;

@doc("CanonicalNameRecord properties")
model CanonicalNameRecordResourceProperties {
  @doc("Gets the CNAME")
  cName: string;

  @doc("Provisioning state")
  @visibility("read")
  provisioningState?: CanonicalNameRecordProvisioningState;
}

@doc("CanonicalNameRecord Resource")
model CanonicalNameRecordResource
  is ProxyResource<CanonicalNameRecordResourceProperties> {
  @doc("The name of resource.")
  @pattern("^[a-zA-Z0-9-]{3,24}$")
  @key("resourceName")
  @segment("canonicalNameRecord") // start with lower case
  @visibility("read")
  @path
  name: string;
}

@doc("Provisioning status of the resource.")
enum CanonicalNameRecordProvisioningState {
  ...ResourceProvisioningState,

  @doc("Accepted State")
  Accepted,
}

#suppress "@azure-tools/typespec-azure-resource-manager/no-resource-delete-operation" "The resource must have a delete operation.TypeSpec"
@armResourceOperations
interface CanonicalNameRecords {
  createOrUpdate is ArmResourceCreateOrUpdateAsync<CanonicalNameRecordResource>;
  listBySubscription is ArmListBySubscription<CanonicalNameRecordResource>;
  listByResourceGroup is ArmResourceListByParent<CanonicalNameRecordResource>;
  get is ArmResourceRead<CanonicalNameRecordResource>;
}
