emit:
  - "@azure-tools/typespec-autorest"
  - "@azure-tools/typespec-providerhub-controller"

options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: ./swagger/voiceservices/resource-manager
    examples-directory: ./examples
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/voiceservices.json"
    emitter-output-dir: "{output-dir}"

  "@azure-tools/typespec-providerhub-controller":
    emitter-output-dir: "{output-dir}/generated"
