output-dir: '{project-root}'
emit:
- '@azure-tools/typespec-autorest'
- '@azure-tools/typespec-providerhub-controller'
options:
  '@azure-tools/typespec-autorest':
    emitter-output-dir: '{output-dir}\{emitter-name}\'
    output-file: '{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/throttling.json'
    azure-resource-provider-folder: '..\..\..\..\specification\throttling\resource-manager\'
    examples-directory: examples
    arm-types-dir: '../../../../../common-types/resource-management/v4/types.json'
  '@azure-tools/typespec-providerhub-controller':
    emitter-output-dir: '{output-dir}\{emitter-name}\'
    registration-output-path: '..\..\..\src\TypeSpec\rpaas\OneBox\'