emit:
  - "@azure-tools/typespec-autorest"
parameters:
  "service-directory-name":
    default: "devtunnels"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: ./swagger/devtunnels/resource-manager
    output-file: devtunnels.json
    examples-directory: ./examples
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
