output-dir: "{project-root}/../"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{output-dir}"
    azure-resource-provider-folder: "."
    new-line: lf
    arm-types-dir: "{project-root}/../../../common-types/resource-management"
  